<?php
defined( 'ABSPATH' ) || exit; // Exit if accessed directly

/**
 * Class WFACP_Importer
 * Handles Importing of Aero Checkout Pages Export JSON file
 */
if ( ! class_exists( 'WFACP_Importer' ) ) {
	#[AllowDynamicProperties]
	class WFACP_Importer {

		private static $ins = null;
		public $is_imported = false;

		public function __construct() {
			if ( ! function_exists( 'WP_Filesystem' ) ) {
				require_once ABSPATH . 'wp-admin/includes/file.php';
			}

			WP_Filesystem();

			require_once WFACP_PLUGIN_DIR . '/includes/class-wfacp-content-validator.php'; //phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingCustomConstant
			WFACP_Content_Validator::register_http_guard();

			$is_admin_enabled = ! class_exists( 'WFFN_Pro_Checkout_Support' )
				|| ! method_exists( 'WFFN_Pro_Checkout_Support', 'is_admin_enabled' )
				|| WFFN_Pro_Checkout_Support::is_admin_enabled();
			if ( ! $is_admin_enabled ) {
				return;
			}

			if ( isset( $_POST['wfacp-action'] ) && 'import' === $_POST['wfacp-action'] ) { //phpcs:ignore WordPress.Security.NonceVerification.Missing,FunnelBuilder.CodeAnalysis.FunnelBuilderSpecific.MissingCapabilityCheck -- Capability verified in maybe_import via user_access
				add_action( 'admin_init', array( $this, 'maybe_import' ) );
			}
		}

		/**
		 * @return WFACP_Importer|null
		 */
		public static function get_instance() {
			if ( null === self::$ins ) {
				self::$ins = new self();
			}

			return self::$ins;
		}

		/**
		 * Import our exported file
		 *
		 * @since 1.1.4
		 */
		function maybe_import() {
			if ( empty( $_POST['wfacp-action'] ) || 'import' != $_POST['wfacp-action'] ) { //phpcs:ignore WordPress.Security.NonceVerification.Missing,FunnelBuilder.CodeAnalysis.FunnelBuilderSpecific.MissingCapabilityCheck
				return;
			}
			if ( ! wp_verify_nonce( isset( $_POST['wfacp-action-nonce'] ) ? sanitize_text_field( wp_unslash( $_POST['wfacp-action-nonce'] ) ) : '', 'wfacp-action-nonce' ) ) {
				return;
			}

			$user = WFACP_Core()->role->user_access( 'checkout', 'write' );
			if ( false === $user ) {
				return;
			}

			// phpcs:disable WordPress.Security.ValidatedSanitizedInput.InputNotValidated,WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- $_FILES values are server-generated by PHP's upload mechanism
			$filename  = sanitize_file_name( isset( $_FILES['file']['name'] ) ? wp_unslash( $_FILES['file']['name'] ) : '' );
			$file_info = explode( '.', $filename );
			$extension = end( $file_info );

			if ( 'json' != $extension ) {
				wp_die( esc_html__( 'Please upload a valid .json file', 'woofunnels-aero-checkout' ) );
			}

			$file = isset( $_FILES['file']['tmp_name'] ) ? $_FILES['file']['tmp_name'] : '';
			// phpcs:enable WordPress.Security.ValidatedSanitizedInput.InputNotValidated,WordPress.Security.ValidatedSanitizedInput.InputNotSanitized

			if ( empty( $file ) ) {
				wp_die( esc_html__( 'Please upload a file to import', 'woofunnels-aero-checkout' ) );
			}
			$content = file_get_contents( $file ); //phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_read_file_get_contents
			$content = utf8_decode( $content );
			$content = trim( $content, '?' );
			// Retrieve the settings from the file and convert the JSON object to an array.
			$acps = json_decode( $content, true );

			$this->import_from_json_data( $acps );

			$this->is_imported = true;
		}

		public function import_from_json_data( $acps ) {
			$imported_acps = array();

			foreach ( $acps as $acp ) {
				$acp_id = 0;
				if ( isset( $acp['id'] ) && ! empty( $acp['id'] ) ) {
					$acp_id = $acp['id'];
				}

				$acp_post = null;
				if ( $acp_id !== 0 ) {
					$acp_post = get_post( $acp_id );
				}

				$acp_title = $acp['title'];
				if ( null !== $acp_post && $acp_title === $acp_post->post_title ) {
					$acp_title = $acp_title . ' Copy';
				}

				$acp_post_args = array(
					'post_title'   => $acp_title,
					'post_type'    => WFACP_Common::get_post_type_slug(),
					'post_content' => isset( $acp['post_content'] ) ? $acp['post_content'] : '',
					'post_status'  => isset( $acp['post_status'] ) ? $acp['post_status'] : 'published',
				);
				$acp_id        = wp_insert_post( $acp_post_args );

				if ( $acp_id !== 0 && isset( $acp['meta'] ) && is_array( $acp['meta'] ) ) {
					$acp_meta = $acp['meta'];

					// Import every Aero Checkout page meta
					$acp_meta = apply_filters( 'wfacp_json_importer_meta', $acp_meta );

					if ( isset( $acp_meta['_wfacp_fieldsets_data'] ) ) {
						$acp_meta['_wfacp_fieldsets_data'] = $this->normalize_address_divider_positions( $acp_meta['_wfacp_fieldsets_data'] );
					}

					foreach ( $acp_meta as $meta_key => $meta_value ) {
						update_post_meta( $acp_id, $meta_key, $meta_value );
					}

					// Import the customizer setting

					$customizer_meta = isset( $acp['customizer_meta'] ) ? $acp['customizer_meta'][ WFACP_SLUG . '_c_' ] : array();

					if ( ! empty( $customizer_meta ) ) {
						$customizer_meta = apply_filters( 'wfacp_json_importer_customizer_meta', $customizer_meta );
						$customizer_meta = $this->import_customizer_image_urls( $customizer_meta );
						update_option( WFACP_SLUG . '_c_' . $acp_id, $customizer_meta, 'no' );
					}

					if ( isset( $acp_meta['_wfacp_selected_design'] ) && isset( $acp_meta['_wfacp_selected_design']['selected_type'] ) && 'elementor' === $acp_meta['_wfacp_selected_design']['selected_type'] ) {
						if ( class_exists( 'WFACP_Elementor_Importer' ) && defined( 'ELEMENTOR_VERSION' ) ) {
							if ( version_compare( ELEMENTOR_VERSION, '3.1.0', '<=' ) ) {
								\Elementor\Plugin::$instance->db->set_is_elementor_page( $acp_id, true );
							} else {
								\Elementor\Plugin::$instance->documents->get( $acp_id )->set_is_built_with_elementor( true );
							}
							$obj                   = new WFACP_Elementor_Importer();
							$obj->delete_page_meta = false;
							$elementor_data        = is_string( $acp_meta['_elementor_data'] ) ? $acp_meta['_elementor_data'] : json_encode( $acp_meta['_elementor_data'] ); //phpcs:ignore WordPress.WP.AlternativeFunctions.json_encode_json_encode
							$obj->import_aero_template( $acp_id, $elementor_data );
						}
					}

					if ( isset( $acp_meta['_wfacp_selected_design'] ) && isset( $acp_meta['_wfacp_selected_design']['selected_type'] ) && 'gutenberg' === $acp_meta['_wfacp_selected_design']['selected_type'] ) {
						$temp_post               = get_post( $acp_id );
						$temp_post->post_content = $acp['post_content'];
						wp_update_post( $temp_post );
					}

					do_action( 'wfacp_acp_imported', $acp_id, $acp, $customizer_meta );

					$imported_acps[] = $acp_id;
				}
			}

			return $imported_acps;
		}

		/**
		 * Reposition the address divider entries in the fieldsets data.
		 *
		 * Export files that round-tripped through a JS object have the
		 * `wfacp_start_divider_*` / `wfacp_end_divider_*` keys pushed after the
		 * integer-keyed fields, which renders the address divider empty and breaks
		 * the shipping-to-billing address copy. Move each divider pair back around
		 * its address group fields.
		 *
		 * @param array $fieldsets_data Value of the `_wfacp_fieldsets_data` meta.
		 *
		 * @return array
		 */
		public function normalize_address_divider_positions( $fieldsets_data ) {
			if ( ! is_array( $fieldsets_data ) || empty( $fieldsets_data['fieldsets'] ) || ! is_array( $fieldsets_data['fieldsets'] ) ) {
				return $fieldsets_data;
			}

			foreach ( $fieldsets_data['fieldsets'] as $step => $sections ) {
				if ( ! is_array( $sections ) ) {
					continue;
				}
				foreach ( $sections as $section_index => $section ) {
					if ( empty( $section['fields'] ) || ! is_array( $section['fields'] ) ) {
						continue;
					}
					$fieldsets_data['fieldsets'][ $step ][ $section_index ]['fields'] = $this->wrap_address_groups_in_dividers( $section['fields'] );
				}
			}

			return $fieldsets_data;
		}

		/**
		 * Move `wfacp_start_divider_*` / `wfacp_end_divider_*` entries so they wrap
		 * the fields of their address group within a section's fields map.
		 *
		 * @param array $fields Section fields keyed by index or divider key.
		 *
		 * @return array
		 */
		protected function wrap_address_groups_in_dividers( $fields ) {
			foreach ( array( 'billing', 'shipping' ) as $type ) {
				$start_key = 'wfacp_start_divider_' . $type;
				$end_key   = 'wfacp_end_divider_' . $type;
				if ( ! isset( $fields[ $start_key ] ) || ! isset( $fields[ $end_key ] ) ) {
					continue;
				}

				$group_keys = array();
				foreach ( $fields as $key => $field ) {
					if ( $start_key === $key || $end_key === $key ) {
						continue;
					}
					if ( is_array( $field ) && ! empty( $field['address_group'] ) && isset( $field['id'] ) && 0 === strpos( $field['id'], $type . '_' ) ) {
						$group_keys[] = $key;
					}
				}
				if ( empty( $group_keys ) ) {
					continue;
				}

				$first_key  = reset( $group_keys );
				$last_key   = end( $group_keys );
				$new_fields = array();
				foreach ( $fields as $key => $field ) {
					if ( $start_key === $key || $end_key === $key ) {
						continue;
					}
					if ( $key === $first_key ) {
						$new_fields[ $start_key ] = $fields[ $start_key ];
					}
					$new_fields[ $key ] = $field;
					if ( $key === $last_key ) {
						$new_fields[ $end_key ] = $fields[ $end_key ];
					}
				}
				$fields = $new_fields;
			}

			return $fields;
		}

		// Import Images from URLs

		protected function import_customizer_image_urls( $data ) {

			$image_keys = array(
				'wfacp_testimonials_0_section_testimonials' => array( 'timage' ),
				'wfacp_assurance_0_section_mwidget_listw' => array( 'mwidget_image' ),
				'wfacp_promises_0_section_promise_icon_text' => array( 'promises_icon' ),
				'wfacp_header_section_logo',
				'wfacp_product_section_product_image',
				'wfacp_gbadge_section_layout_1_custom_list_image',
				'wfacp_customer_0_section_supporter_image',
				'wfacp_customer_0_section_supporter_signature_image',
			);

			foreach ( $image_keys as $key => $value ) {
				if ( is_array( $value ) ) {
					$img_key = $value[0];

					if ( isset( $data[ $key ] ) && is_array( $data[ $key ] ) ) {
						foreach ( $data[ $key ] as $k => $v ) {
							$img = $v[ $img_key ];

							if ( ! empty( $img ) ) {
								$data[ $key ][ $k ][ $img_key ] = $this->import_image( $img );
							}
						}
					}
				} elseif ( is_string( $value ) ) {
					$img_key = $value;

					if ( ! empty( $data[ $img_key ] ) ) {
						$data[ $img_key ] = $this->import_image( $data[ $img_key ] );
					}
				}
			}

			return $data;
		}

		protected function import_image( $url ) {

			$saved_image = $this->get_saved_image( $url );

			if ( $saved_image ) {
				return $saved_image;
			}

			// Extract the file name and extension from the url.
			$filename = basename( $url );

			require_once WFACP_PLUGIN_DIR . '/includes/class-wfacp-content-validator.php'; //phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingCustomConstant
			WFACP_Content_Validator::begin_import();
			$file_content = wp_remote_retrieve_body(
				wp_safe_remote_get(
					$url,
					array(
						'timeout'            => 60, //phpcs:ignore WordPressVIPMinimum.Performance.RemoteRequestTimeout.timeout_timeout
						'sslverify'          => true,
						'reject_unsafe_urls' => true,
						'redirection'        => 0,
					)
				)
			);
			WFACP_Content_Validator::end_import();

			if ( empty( $file_content ) ) {
				return false;
			}

			$upload = wp_upload_bits( $filename, null, $file_content );

			if ( ! empty( $upload['error'] ) ) {
				return $url;
			}

			$post = array(
				'post_title' => $filename,
				'guid'       => $upload['url'],
			);

			$info = wp_check_filetype( $upload['file'] );
			if ( $info ) {
				$post['post_mime_type'] = $info['type'];
			} else {
				return $url;
			}

			if ( ! function_exists( 'wp_generate_attachment_metadata' ) ) {
				require_once ABSPATH . 'wp-admin/includes/image.php';
			}

			$post_id = wp_insert_attachment( $post, $upload['file'] );
			wp_update_attachment_metadata( $post_id, wp_generate_attachment_metadata( $post_id, $upload['file'] ) );
			update_post_meta( $post_id, '_bwf_source_image_hash', $this->get_hash_image( $url ) );

			return $upload['url'];
		}

		private function get_saved_image( $url ) {

			global $wpdb;
			$post_id = $wpdb->get_var(
				$wpdb->prepare(
					'SELECT `post_id` FROM `' . $wpdb->postmeta . '`
					WHERE `meta_key` = \'_bwf_source_image_hash\'
						AND `meta_value` = %s
				;',
					$this->get_hash_image( $url )
				)
			); //phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching

			if ( $post_id ) {
				return wp_get_attachment_url( $post_id );
			}

			return false;
		}

		private function get_hash_image( $attachment_url ) {
			return sha1( $attachment_url );
		}

		public function allow_known_hosts( $allow, $host ) {
			$allowed_hosts = WFACP_Content_Validator::get_allowed_import_hosts();

			if ( in_array( $host, $allowed_hosts, true ) ) {
				return true;
			}

			return $allow;
		}

		public function imported_successfully() {
			?>
			<div class="notice notice-success is-dismissible">
				<p><?php esc_html_e( 'Imported Successfully!', 'woofunnels-aero-checkout' ); ?></p>
			</div>
			<?php
		}
	}


	if ( class_exists( 'WFACP_Core' ) ) {
		WFACP_Core::register( 'import', 'WFACP_Importer' );
	}
}
