<?php
// Generated by bin/build-classmap.php — do not edit by hand.
// FQCN => path relative to this directory. Files doing work at include time are
// intentionally absent (see the generator) and stay explicit includes.
return [
    'FilterEverything\\Filter\\LicenseTab' => 'Settings/Tabs/LicenseTab.php',
    'FilterEverything\\Filter\\Pro\\Admin\\Admin' => 'Admin/Admin.php',
    'FilterEverything\\Filter\\Pro\\Admin\\ExportSettings' => 'Admin/ExportSettings.php',
    'FilterEverything\\Filter\\Pro\\Admin\\ImportSettings' => 'Admin/ImportSettings.php',
    'FilterEverything\\Filter\\Pro\\Admin\\SeoRulesPreview' => 'Admin/SeoRulesPreview.php',
    'FilterEverything\\Filter\\Pro\\Api\\ApiRequests' => 'Api/ApiRequests.php',
    'FilterEverything\\Filter\\Pro\\Entities\\PostMetaExistsEntity' => 'Entities/PostMetaExistsEntity.php',
    'FilterEverything\\Filter\\Pro\\Entities\\TaxonomyNumEntity' => 'Entities/TaxonomyNumEntity.php',
    'FilterEverything\\Filter\\Pro\\PluginPro' => 'PluginPro.php',
    'FilterEverything\\Filter\\Pro\\SeoFrontend' => 'SeoFrontend.php',
    'FilterEverything\\Filter\\Pro\\Settings\\Tabs\\ImportExportTab' => 'Settings/Tabs/ImportExportTab.php',
    'FilterEverything\\Filter\\Pro\\Settings\\Tabs\\IndexingDepth' => 'Settings/Tabs/IndexingDepth.php',
    'FilterEverything\\Filter\\Pro\\Settings\\Tabs\\SeoRulesTab' => 'Settings/Tabs/SeoRulesTab.php',
    'FilterEverything\\Filter\\Pro\\ShortcodesPro' => 'Admin/ShortcodesPro.php',
    'FilterEverything\\Filter\\Pro\\WriteXml' => 'Xml/WriteXml.php',
    'FilterEverything\\Filter\\Pro\\XmlPrepare' => 'Xml/XmlPrepare.php',
];
