<?php

if ( ! defined('ABSPATH') ) {
    exit;
}

use FilterEverything\Filter\Pro\Admin\Admin;
use FilterEverything\Filter\Container;

if( ! class_exists('FiltersPro') ):

class FiltersPro{

    function __construct()
    {
        $wpcFilter = flrt_filter();
        $wpcFilter->define( 'FLRT_SEO_RULES_POST_TYPE', 'filter-seo-rule' );
        $wpcFilter->define( 'FLRT_FILTERS_PRO', true );
        $wpcFilter->define( 'FLRT_ENVATO_APP_CLIENT_ID', 'filter-everything-py1gbdtg' );
        $wpcFilter->define( 'FLRT_VERSION_TRANSIENT', 'wpc_plugin_version' );
        $wpcFilter->define( 'FLRT_PRO_BUILDER_KEY', '_kl-jlk_45(dp*)sd' );
        $wpcFilter->define( 'FLRT_LICENSE_SOURCE', 'https://filtereverything.pro/pricing/' );

        // PRO classes are autoloaded from pro/classmap.php (generated by bin/build-classmap.php).
        // Registering the map here — and only here — is what makes the free/PRO switch a single line.
        \FilterEverything\Filter\Autoloader::addClassMap( require __DIR__ . '/classmap.php', __DIR__ );
        \FilterEverything\Filter\Autoloader::addNamespace( 'FilterEverything\\Filter\\Pro', __DIR__ );

        // Files that do work at include time — kept explicit, in their historical order.
        flrt_include('pro/wpc-license-token.php');
        flrt_include('pro/wpc-default-hooks-pro.php');
        flrt_include('pro/wpc-utility-functions.php');
        flrt_include('pro/PostTypes.php');
        flrt_include('pro/RobotsTxtFile.php');
        flrt_include('pro/Admin/SeoRules.php');
        flrt_include('pro/Admin/MetaBoxes.php');

        if( is_admin() ){
            new Admin();
        }

        add_action( 'init', [ $this, 'init'] );
        add_action( 'wp', [ $this, 'wpInit'], -1 );
    }

    public function wpInit()
    {
        $seoFrontend = Container::instance()->getSeoFrontendService();
        $seoFrontend->processPageSeo();
    }

    public function init()
    {
        if ( is_multisite() ) {
            if( is_main_site() ) {
                flrt_init_common();
            } else {
                flrt_init_common_multisite();
            }
        } else {
            flrt_init_common();
        }
    }
}

new FiltersPro();

endif;